name: example
description: "A flutter_audio_games example."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-210.4.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.9.0
  cupertino_icons: ^1.0.2
  dart_synthizer: ^0.11.2
  flutter:
    sdk: flutter
  flutter_audio_games:
    path: ..
  flutter_riverpod: ^2.4.6
  flutter_synthizer: ^0.8.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - sounds/ambiances/
    - sounds/combat/
    - sounds/footsteps/
    - sounds/menus/
    - sounds/music/
    - sounds/zombies/breathing/
    - sounds/zombies/death/
    - sounds/zombies/sayings/
    - sounds/zombies/hits/
