name: flutter_audio_games
version: 0.9.1
description: "Widgets useful for creating audio games."
homepage: https://github.com/chrisnorman7/flutter_audio_games
environment:
  sdk: ">=3.1.0<4.0.0"
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.9.0
  dart_synthizer: ^0.11.2
  flutter:
    sdk: flutter
  flutter_synthizer: ^0.3.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
