name: flutter_audio_games
description: "Widgets useful for creating audio games."
version: 0.0.1
homepage: https://github.com/chrisnorman7/flutter_audio_games
publish_to: "none"
environment:
  sdk: ">=3.2.0-210.4.beta <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.8.0
  dart_synthizer: ^0.11.2
  flutter:
    sdk: flutter
  flutter_synthizer: ^0.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
