name: flutter_audio_games
version: 0.31.0
description: "Widgets useful for creating audio games."
repository: https://github.com/chrisnorman7/flutter_audio_games
environment:
  sdk: ">=3.1.0<4.0.0"
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.21.0
  flutter:
    sdk: flutter
  flutter_soloud: ^2.1.5
  http: ^1.2.2
  logging: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
