name: flutter_audio_games
version: 0.28.0
description: "Widgets useful for creating audio games."
repository: https://github.com/chrisnorman7/flutter_audio_games
environment:
  sdk: ">=3.1.0<4.0.0"
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.16.0
  flutter:
    sdk: flutter
  flutter_soloud: ^2.1.3
  http: ^1.2.2
  logging: ^1.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
