name: flutter_audio_games
version: 0.33.0
description: A package which makes it easy to write audio games in Flutter.
homepage: https://github.com/chrisnorman7/flutter_audio_games
environment:
  sdk: ">=3.1.0<4.0.0"
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.27.1
  flutter:
    sdk: flutter
  flutter_soloud: ^2.1.7
  http: ^1.2.2
  logging: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
