name: flutter_audio_games
version: 0.48.3
description: A package which makes it easy to write audio games in Flutter.
homepage: https://github.com/chrisnorman7/flutter_audio_games
environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.35.0
  flutter:
    sdk: flutter
  flutter_soloud: ^3.2.2
  http: ^1.3.0
  logging: ^1.3.0
  path: ^1.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
