name: example
description: "A flutter_audio_games example."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-210.4.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.22.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_audio_games:
    path: ../../flutter_audio_games
  flutter_riverpod: ^2.5.1
  flutter_soloud: ^2.1.7
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
  assets:
    - sounds/ambiances/
    - sounds/combat/
    - sounds/footsteps/
    - sounds/menus/
    - sounds/music/
    - sounds/zombies/breathing/
    - sounds/zombies/death/
    - sounds/zombies/sayings/
    - sounds/zombies/hits/
