name: side_scroller
description: "Side scroller example."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  backstreets_widgets: ^0.17.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_audio_games:
    path: ../../flutter_audio_games
  flutter_soloud: ^2.1.4
  flutter_tts: ^4.0.2
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - sounds/ambiances/
    - sounds/footsteps/porch/
    - sounds/footsteps/stone/
    - sounds/weapons/
